-- -------------------------------------------------------------------------- --
--                                 RadialTools                                --
-- -------------------------------------------------------------------------- --
-- -------------------------- Written by HavocOmega ------------------------- --
-- ------------------------------ Version 1.0.0 ----------------------------- --

-- -------------------------------- Services -------------------------------- --
local ChangeHistoryService = game:GetService("ChangeHistoryService")

-- ---------------------------------- Paths --------------------------------- --
local Packages = script.Packages
local CoreGui: CoreGui = game:GetService("CoreGui")

-- --------------------------------- Imports -------------------------------- --
local Roact = require(Packages.Roact)

-- ---------------------------- Private Functions --------------------------- --
local function InitiaizeUI()
    local MainUI = Roact.createElement("ScreenGui")
end